clear;
close all;
clc;

disp("Simulation started")

setSysParams;
setObstacles;
setMPCParams;
setPlannerParams;
setPathfgParams;
computeAndPack;

rrtFcn();

global fig1;
fig1 = figure(Position=[0, 0, 800, 2400]);

% loop over all the path planners
path_planner = path_planners(path_planner_idx);
pathPlanner;
prediction_horizon_MPC = prediction_horizons_MPC(1);
setMPCParameters;
setStructs;

sim_start = tic;
disp("Simulink simulation started");
sim_out = sim("sim.slx");
disp("Simulink simulation ended");
sim_time = toc(sim_start);
disp(strcat("Total simulation time: ", num2str(sim_time)));

plotGraphSingleN( ...
    sim_out.reference_signal, ...
    sim_out.non_linear_full_states, ...
    sim_out.pathFG_time, ...
    sim_out.MPC_time, ...
    sim_out.ctrl_inputs, ...
    colors, ...
    goal, ...
    prediction_horizon_MPC, ...
    sim_out.aux_ref_params, ...
    path, ...
    sim_out.MPC_iterations, ...
    inner_controller_inclusion, ...
    mass_true, ...
    g, ...
    simulation_length, ...
    u_min, ...
    u_max, ...
    x_min, ...
    x_max...
);

disp("Simulation ended");