function [full_state_dot, body_rates, body_accel] = linearModel( ...
    thrusts, ...
    full_state, ...
    A_continuous, ...
    B_continuous,...
    g, ...
    mass_true)

    equilibrium_thrust_per_propeller = mass_true * g /4;
    thrusts = thrusts - equilibrium_thrust_per_propeller;

    % dummy value (body_accel is unused)
    body_accel = zeros(3, 1);

    % linear approximation of the nonlinear model
    full_state_dot = A_continuous * full_state + B_continuous * thrusts;

    % compute the T matrix for transforming psi_dot into omega
    roll = full_state(7);
    pitch = full_state(8);
    T = [...
            1,  0        , -sin(pitch)          ;...
            0,  cos(roll),  sin(roll)*cos(pitch);...
            0, -sin(roll),  cos(roll)*cos(pitch) ...
        ];

    % compute the body angular rates, omega
    body_rates = T * full_state_dot(7:9);

end
