function [full_state_dot,body_rates,body_accel] = nonlinearModel( ...
    thrusts, ...
    full_state, ...
    g, ...
    mass_true, ...
    inertia_true, ...
    inertia_true_inverse, ...
    layout_true)

    % Non-linear euqations of motion of quadrotor

    % Extract the components of the full state
    %pos      =  full_state(1:3);
    pos_dot  =  full_state(4:6);
    psi      =  full_state(7:9);
    psi_dot  =  full_state(10:12);
    
    
    % Extract each Euler angles
    roll   =  psi(1);  % Roll  
    pitch  =  psi(2);  % Pitch 
    yaw    =  psi(3);  % Yaw
    
    
    % Extract each Euler anglular rates
    roll_dot   =  psi_dot(1);  % Roll  angular velocity
    pitch_dot  =  psi_dot(2);  % Pitch angular velocity
    %yaw_dot    =  psi_dot(3); % Yaw   angular velocity, not needed
    
    
    % Compute the rotation matrix from body frame to inertial frame:
    R_B2I = [...
                cos(yaw)*cos(pitch)  ,...
                    cos(yaw)*sin(pitch)*sin(roll)-sin(yaw)*cos(roll)  ,...
                    cos(yaw)*sin(pitch)*cos(roll)+sin(yaw)*sin(roll)   ...
                ;...
                sin(yaw)*cos(pitch)  ,...
                    sin(yaw)*sin(pitch)*sin(roll)+cos(yaw)*cos(roll)  ,...
                    sin(yaw)*sin(pitch)*cos(roll)-cos(yaw)*sin(roll)   ...
                ;...
                -sin(pitch)  ,...
                    cos(pitch)*sin(roll)  ,...
                    cos(pitch)*cos(roll)   ...
        ];
    
    
    % Compute the T matrix:
    T = [...
            1  ,  0          ,  -sin(pitch)            ;...
            0  ,  cos(roll)  ,   sin(roll)*cos(pitch)  ;...
            0  , -sin(roll)  ,   cos(roll)*cos(pitch)   ...
        ];
    
    
    % Compute the T inverse matrix:
    T_inv = [...
            1  ,  sin(roll)*tan(pitch)  ,   cos(roll)*tan(pitch)  ;...
            0  ,  cos(roll)             ,  -sin(roll)             ;...
            0  ,  sin(roll)*sec(pitch)  ,   cos(roll)*sec(pitch)   ...
        ];
    
    
    % Compute the time derivative of the T matrix:
    T_dot = [...
            0  ,   0                   ,  -pitch_dot*cos(pitch)                                          ;...
            0  ,  -roll_dot*sin(roll)  ,   roll_dot*cos(roll)*cos(pitch)-pitch_dot*sin(roll)*sin(pitch)  ;...
            0  ,  -roll_dot*cos(roll)  ,  -roll_dot*sin(roll)*cos(pitch)-pitch_dot*cos(roll)*sin(pitch)   ...
        ];
    
    
    % Implement the equation of motion for translation
    pos_double_dot = (1/mass_true) .* ( R_B2I * [0;0;sum(thrusts(:))] ) + [0;0;-g];
    
    
    % Compute the body rates from the Euler angluar rates
    w = T * psi_dot;
    
    
    % Implement the equation of motion for body frame rotations
    w_dot = inertia_true_inverse * ( [layout_true(2,:);-layout_true(1,:);layout_true(3,:)] * thrusts - cross( w , inertia_true * w ) );
    
    
    % Implement the equation of motion for Euler angle rotations
    psi_double_dot = T_inv * ( w_dot - T_dot * psi_dot );

    % Put together the "full_state_dot" return variable
    full_state_dot = [...
            pos_dot ;...
            pos_double_dot ;...
            psi_dot ;...
            psi_double_dot ...
        ];
    
    
    % Put together the "body_rates" return variable
    body_rates = w;

    % Finally compute the accelerations in the body frame
    % > by "simply" rotating the inertial frame linear accelerations, i.e.,
    %   "pos_double_dot", from the inertial frame into the body frame
    % > do you need to account for the fact that the body frame accelerations
    %   are measured in a rotating frame? Yes
    body_accel = transpose(R_B2I) * psi_double_dot; % Original Code 

end