

%% Creat Structs
ssmodel = struct('A', A_discrete_outer, 'B', B_discrete_outer, ...
    'C', C_outer, 'D', D_outer);

weights = struct('N', prediction_horizon_MPC, 'P', P_matrix, ...
    'Q', Q_MPC, 'R', R_MPC, 'K', K_lqr_outer_loop);

agent_params = struct('agent_size', agent_size,...
                    'm', mass_for_controller,...
                    'g', g,...
                    'thrust_max', thrust_max,...
                    'thrust_min', thrust_min);

obs_params = struct('obs_p', obstacles,...
                   'obs_size', obstacle_sizes,...
                   'rectangular_obs',rect_obs);

constr_mat = struct('Q_R_P_weight_matrix', Q_R_P_weight_matrix,...
                    'Aeq', Aeq,...
                    'lb', lb,...
                    'ub', ub); 

dark_blue = [0 0.4470 0.7410];
colors = [
        "#0072BD",...   % a darker blue
        "#ffA500",...   % orange
        "#C64B8C",...   % dark red
        "#77AC30",...   % green
        "#2698D6",...   % medium blue
        "#4DBEEE",...   % light blue
        "#D95319",...   % red
        'black'];