

%% Creat Structs
ssmodel = struct('A', A_discrete_outer, 'B', B_discrete_outer, ...
    'C', C_outer, 'D', D_outer);

weights = struct('N', prediction_horizon_MPC, 'P', LQR_P_matrix_full, ...
    'Q', Q_MPC, 'R', R_MPC, 'K', K_lqr_outer_loop);

agent_params = struct('agent_size', agent_size,...
                    'm', mass_for_controller,...
                    'g', g,...
                    'thrust_max', thrust_max,...
                    'thrust_min', thrust_min);

obs_params = struct('obs_p', obstacles,...
                   'obs_size', obstacle_sizes);

constr_mat = struct('Q_R_P_weight_matrix', Q_R_P_weight_matrix,...
                    'Aeq', Aeq,...
                    'lb', lb,...
                    'ub', ub); 

dark_blue = [0 0.4470 0.7410];
colors = ["#0072BD",... % blue
        "#ffA500",...   % orange
        "#77AC30",...   % green
        "#D95319",...   % red
        "#4DBEEE",...   % light blue
        'black'];