function terminalEnergyDSM_val = terminalEnergyDSM_pathFG( ...
    states_estimates, ...
    applied_reference, ...
    mass_for_controller, ...
    g, ...
    u_max, ...
    u_min, ...
    kappa_s, ...
    kappa_o, ...
    kappa_omega,...
    obstacles, ...
    obstacle_sizes, ...
    agent_size, ...
    K_lqr_outer_loop,...
    P_matrix)
    
    x = states_estimates;
    v = [applied_reference(1:3); 0; 0; 0; 0; 0; applied_reference(4)];
    m = mass_for_controller;

    lyapunov_value = lyapunovValue(x, v, P_matrix);

    [thrust_DSM_value, ~] = thrustDSM(u_max(1)+m*g, u_min(1)+m*g, mass_for_controller, g, lyapunov_value, v, K_lqr_outer_loop, P_matrix, kappa_s);

    [obstacle_DSM_value, ~] = obstacleDSM(obstacles, lyapunov_value, v, P_matrix, obstacle_sizes, agent_size, kappa_o);

    [angular_rate_DSM, ~] = angularRateDSM(v, lyapunov_value, K_lqr_outer_loop, P_matrix, u_max, u_min, kappa_omega);

    % Find the minimum value among the dynamic safety margins
    terminalEnergyDSM_val = min([thrust_DSM_value, obstacle_DSM_value, angular_rate_DSM]);

end