function terminalEnergyDSM_val = terminalEnergyDSM( ...
    states_estimates, ...
    applied_reference, ...
    mass_for_controller, ...
    g, ...
    thrust_max, ...
    thrust_min, ...
    k_P, ...
    k_D, ...
    epsilon, ...
    kappa_s, ...
    kappa_o, ...
    kappa_omega,...
    obstacles, ...
    obstacle_sizes, ...
    agent_size, ...
    DSM_inclusion, ...
    LQR_P_matrix_full, ...
    controller, ...
    K_lqr_outer_loop_discrete_time, ...
    u_min, ...
    u_max)
    
    if not(DSM_inclusion)
        terminalEnergyDSM_val = 1.0;
        return;
    end

    x = states_estimates;
    v = [applied_reference(1:3); 0; 0; 0; 0; 0; applied_reference(4)];
   
    lyapunov_value = lyapunovValue(x, v, LQR_P_matrix_full);

    thrust_DSM_value = thrustDSM(thrust_max, thrust_min, mass_for_controller, g, lyapunov_value, v, K_lqr_outer_loop_discrete_time, LQR_P_matrix_full, kappa_s);
    obstacle_DSM_value = obstacleDSM(obstacles, lyapunov_value, v, LQR_P_matrix_full, obstacle_sizes, agent_size, kappa_o);
    angular_rate_DSM = angularRateDSM(v, lyapunov_value, K_lqr_outer_loop_discrete_time, LQR_P_matrix_full, u_max, u_min, kappa_omega);

    % Find the minimum value among the dynamic safety margins
    terminalEnergyDSM_val = min([thrust_DSM_value, obstacle_DSM_value, angular_rate_DSM]);
    
end