function [flag, DSM_value] = checkDynamicsFeasibility(...
    predicted_states_Nth_step,...
    v, ...
    prediction_horizon_FG, ...
    A_discrete_outer, ...
    B_discrete_outer, ...
    K_lqr_outer_loop_discrete_time,...
    agent_size, ...
    obstacles, ...
    obstacle_sizes, ...
    safety_margin, ...
    x_min, ...
    x_max, ...
    u_min,...
    u_max,...
    delta_FG,...
    mass_for_controller, ...
    g, ...
    thrust_max, ...
    thrust_min, ...
    k_P, ...
    k_D, ...
    epsilon, ...
    kappa_s, ...
    kappa_o, ...
    kappa_omega,...
    DSM_inclusion,...
    scaling_factor_traj_DSM_obstacle, ...
    scaling_factor_traj_DSM_x_bounds, ...
    scaling_factor_traj_DSM_U_bounds,...
    P_matrix, ...
    controller)
        
    % Noted that there is a small difference between the following implementation and
    % the original paper (A terminal State Feasibility Governor for Real-Time Nonlinear
    % Model Predictive Control over Arbitrary Horizons). In the original
    % paper, the input of Dynamic Safety Margin(DSM) are
    % 1) predicted Nth states of k step, 2) auxiliary reference v of k-1
    % step. In the below implementation, the input are 1) predicted Nth states
    % of k-1 step, 2) auxiliary reference v of k-1 step. 

    flag = 1;
    trajectoryBasedDSM_value = realmax("double");

    % Generate predicted_traj and U
    current_x = predicted_states_Nth_step;
    predicted_traj = current_x;
    U = zeros(4,0);
    v_full_states = [v(1);v(2);v(3);0;0;0;0;0;v(4)];
    
    if prediction_horizon_FG > 0

        for k = 1:prediction_horizon_FG
    
            u =  K_lqr_outer_loop_discrete_time * (v_full_states - current_x);
     
            x_next = A_discrete_outer * current_x ...
                + B_discrete_outer * u;
        
            predicted_traj = [predicted_traj, x_next];
            U = [U, u];
    
            current_x  = x_next;
        end

        % Check traj feasibility
        trajectoryBasedDSM_value = trajectoryBasedDSM( ...
            predicted_traj,...
            U,...
            agent_size, ...
            obstacles, ...
            obstacle_sizes, ...
            safety_margin, ...
            x_min, ...
            x_max, ...
            u_min,...
            u_max,...
            delta_FG, ...
            scaling_factor_traj_DSM_obstacle, ...
            scaling_factor_traj_DSM_x_bounds, ...
            scaling_factor_traj_DSM_U_bounds);
    end

    % Check terminal feasibility
    terminalEnergyDSM_val = terminalEnergyDSM(...
        predicted_traj(:, end), ...
        v, ...
        mass_for_controller, ...
        g, ...
        thrust_max, ...
        thrust_min, ...
        k_P, ...
        k_D, ...
        epsilon, ...
        kappa_s, ...
        kappa_o, ...
        kappa_omega,...
        obstacles, ...
        obstacle_sizes, ...
        agent_size, ...
        DSM_inclusion, ...
        P_matrix, ...
        controller, ...
        K_lqr_outer_loop_discrete_time, ...
        u_min, ...
        u_max); 
     
    DSM_value = min(trajectoryBasedDSM_value,terminalEnergyDSM_val);

    if(DSM_value < 0)
        flag = 0;
    end

end