function flag = checkSteadyStateAdmissibility( ...
    agent_position, ...
    agent_size, ...
    obstacle_position, ...
    obstacle_sizes, ...
    safety_margin_universal, ...
    x_min, ...
    x_max, ...
    delta)
    
    flag = 1;

    % Check obstacle collision
    collision_flag = agentObstaclesCollisionCheck( ...
        agent_position, ...
        agent_size, ...
        obstacle_position, ...
        obstacle_sizes, ...
        safety_margin_universal);

    % Check states boundary violation
    x_min_strict = (1 - delta) * x_min;
    x_max_strict = (1 - delta) * x_max;

     if (agent_position(1) < x_min_strict(1) ||...
            agent_position(2) < x_min_strict(2) ||...
            agent_position(3) < x_min_strict(3) ||...
            agent_position(1) > x_max_strict(1) ||...
            agent_position(2) > x_max_strict(2) ||...
            agent_position(3) > x_max_strict(3))
        boundary_violation_flag = 1;
     else
        boundary_violation_flag = 0;
    end

    if (collision_flag == 1 || boundary_violation_flag == 1) % not admissible
        flag = 0;
    end

end