
function padded_predicted_states = POSS(...
                                        predicted_states,...
                                        K,...
                                        current_x_ref,...
                                        A_discrete_outer,...
                                        B_discrete_outer)

    x_ref = [current_x_ref(1,1);...
             current_x_ref(2,1);...
             current_x_ref(3,1);...
             0.0;...
             0.0;...
             0.0;...
             0.0;...
             0.0;...
             current_x_ref(4,1)];
    
    last_x = predicted_states(end-8 : end);
    
    u_LQR = - K * (last_x - x_ref); 
        
    padded_last_x = A_discrete_outer * last_x + B_discrete_outer * u_LQR;

    padded_predicted_states = [predicted_states(14:size(predicted_states,1),1); u_LQR; padded_last_x];

end

