
function padded_predicted_states = POSS_artificial_ref(...
                                        predicted_states,...
                                        K,...
                                        current_x_ref,...
                                        A_discrete_outer,...
                                        B_discrete_outer)

    x_ref = [current_x_ref(1,1);...
             current_x_ref(2,1);...
             current_x_ref(3,1);...
             0.0;...
             0.0;...
             0.0;...
             0.0;...
             0.0;...
             current_x_ref(4,1)];
    
    % The last 3 is artificial reference
    last_x = predicted_states(end-11 : end-3);
    
    u_LQR = - K * (last_x - x_ref); 
        
    padded_last_x = A_discrete_outer * last_x + B_discrete_outer * u_LQR;

    padded_predicted_states = [predicted_states(14:size(predicted_states,1)-3,1); u_LQR; padded_last_x,predicted_states(end-2 : end)];

end

